[project]
name = "try-multi-nodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepspeed>=0.17.5",
    "pytorch-lightning>=2.5.4",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
