[workspace]
authors = ["Trong Thang Pham <phamtrongthang123@gmail.com>"]
channels = ["conda-forge"]
name = "testing_code"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
opencv = ">=4.12.0,<5"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=4.1.1,<5"
compilers = ">=1.11.0,<2"
gxx_linux-64 = ">=14.3.0,<15"
cuda-toolkit = ">=11.0,<12"
cuda-nvcc = ">=11.0,<12"
